/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExchangePriceDto } from './exchangePriceDto';


export interface ArbitrageDto { 
    allPrices?: { [key: string]: { [key: string]: ExchangePriceDto; }; };
    exchangeNameBuy?: string;
    exchangeNameSell?: string;
    numOfTokens?: string;
    tokenName?: string;
    usdEquivalentBuy?: string;
    usdEquivalentSell?: string;
}
